local file = assert(io.open("Integrations/MDTAdapter.lua", "rb"))
local source = file:read("*a")
file:close()
assert(source:find('["6.2.2"] = true', 1, true), "MDT 6.2.2 must be source-verified")
assert(source:find('DungeonEnemies_AddOrRemoveBlipToCurrentPull', 1, true), "official MDT membership mutator must be hooked")
assert(source:find('function Adapter:ValidateExecutionFreshness(reason)', 1, true), "combat-entry freshness check is missing")
assert(source:find('route-watch-baseline-unavailable', 1, true), "missing baseline must fail closed")
assert(source:find('route-signature-changed', 1, true), "changed route must fail closed")
print("ok - MDT adapter mutation and freshness guards")
