local file = assert(io.open("Runtime/MarkerExecutor.lua", "rb"))
local source = file:read("*a")
file:close()
assert(source:find('local function validateRuntimeExecutionContext(runtimeState)', 1, true), "shared execution gate is missing")
assert(source:find('if executionInvalidated then return nil', 1, true), "invalidated execution must fail closed")
assert(source:find('local MAX_ROUTE_BATCHES = 3', 1, true), "maximum route batch invariant changed")
assert(source:find('if #result > BULK_MARKER_LIMIT then', 1, true), "per-batch marker cap is missing")
assert(source:find('function Executor:InvalidateExecution(reason)', 1, true), "execution invalidation entrypoint is missing")
print("ok - marker executor gates and capacity invariants")
