local function read(path)
  local file = assert(io.open(path, "rb"), "missing " .. path)
  local text = file:read("*a")
  file:close()
  return text
end

local toc = read("MDTPullMarker.toc")
local readme = read("README.md")
local changelog = read("CHANGELOG.md")
local compatibility = read("COMPATIBILITY.md")
local audit = read("COMPARABLE_ADDON_AUDIT-2026-08-21.md")
local commands = read("Core/Commands.lua")
local compartment = read("Core/AddonCompartment.lua")

local version = toc:match("## Version:%s*([^\r\n]+)")
assert(version == "1.0.0-rc63", "unexpected TOC version")
assert(readme:find("# MDT Pull Marker " .. version, 1, true), "README version must match TOC")
assert(changelog:find("## " .. version .. " ", 1, true), "changelog release identity must match TOC")
assert(compatibility:find("# Compatibility — " .. version, 1, true), "compatibility document version must match TOC")
assert(compatibility:find("MDT 6.2.12", 1, true), "current MDT compatibility baseline must remain documented")
assert(compatibility:find("5c9413ffde853e71c8fe3f1864dc5ae42e301f64", 1, true), "MDT 6.2.12 source-review commit must stay pinned")
assert(compatibility:find("preserveExistingTargetMarkers", 1, true), "MDT Focus Marker preserve-existing contract must stay documented")
assert(compatibility:find("RegisterUIInitializer", 1, true), "MDT load-on-demand UI initializer contract must stay documented")
assert(readme:find("/mdtpm plan <pull>", 1, true), "safe local preview must be documented")
assert(toc:find("## AddonCompartmentFunc: MDTPullMarker_Open", 1, true), "addon compartment entry must remain registered")
assert(toc:find("Core\\Commands.lua\nCore\\AddonCompartment.lua\n", 1, true), "compartment module must load after Commands so Addon.Commands is available")
assert(not commands:find("function MDTPullMarker_Open", 1, true), "Commands.lua must not own compartment globals")
assert(not commands:find("function MDTPullMarker_CompartmentEnter", 1, true), "Commands.lua must not own compartment enter")
assert(not commands:find("function MDTPullMarker_CompartmentLeave", 1, true), "Commands.lua must not own compartment leave")
assert(compartment:find("function MDTPullMarker_Open(_, buttonName)", 1, true), "compartment click owner missing")
assert(compartment:find("function MDTPullMarker_CompartmentEnter(_, menuButtonFrame)", 1, true), "AddOn Compartment enter signature missing")
assert(compartment:find('GameTooltip:SetOwner(menuButtonFrame, "ANCHOR_LEFT")', 1, true), "tooltip must anchor to the actual compartment frame")
assert(toc:find("## Category: Dungeons & Raids", 1, true), "native addon category missing")
for _, locale in ipairs({ "deDE", "esES", "esMX", "frFR", "itIT", "koKR", "ptBR", "ruRU", "zhCN", "zhTW" }) do
  assert(toc:find("## Category-" .. locale .. ":", 1, true), "localized addon category missing: " .. locale)
end
assert(audit:find("Mythic Dungeon Tools - Next Pull Tracker", 1, true), "comparison evidence missing Next Pull Tracker")
assert(audit:find("WarpDeplete", 1, true), "comparison evidence missing WarpDeplete")
assert(audit:find("Angry Keystones", 1, true), "comparison evidence missing Angry Keystones")
assert(audit:find("MythicPlusTimer", 1, true), "comparison evidence missing MythicPlusTimer")

print("ok - comparable addon metadata/preview/version/compatibility/changelog/compartment ownership contract")
